services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: LeashPals
      DB_USER: postgres
      DB_PASSWORD: Destinyosiris044
      JWT_SECRET: jwtsecret
    ports:
      - 42069:42069
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Destinyosiris044
      POSTGRES_DB: LeashPals
    ports:
      - 5432:5432
